# -*- coding: utf-8 -*-
"""studentperformance_processessed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JK5zqrTTQp3ffGBLe4647sECG8GbPMrP
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("studentperformance_preprocessed.csv")

df.head()

df.tail()

df.info()

df.describe()

df.columns

df.shape

df.isnull().sum()

score_columns=['math score','reading score','writing score']

df[score_columns].head()

demographic_columns=['gender','race/ethnicity','parental level of education','lunch','test preparation course']

df[demographic_columns].head()

df['gender'].unique()

df['parental level of education'].unique()

df['lunch'].head()

df['test preparation course'].head()

sns.set_theme(style="whitegrid")

plt.figure(figsize=(14, 7))
sns.barplot(
    x='parental level of education',
    y='Percentage',
    hue='lunch',
    data=df,
    estimator=np.mean,
    errorbar=None,
    palette='muted'
)

plt.title('Average Test Score Percentage by Parental Education and Lunch Type', fontsize=16)
plt.xlabel('Parental Level of Education', fontsize=12)
plt.ylabel('Average Percentage (%)', fontsize=12)
plt.xticks(rotation=15)
plt.legend(title='Lunch Type', loc='upper right')
plt.tight_layout()

plt.show()

sns.set_theme(style="whitegrid")

score_melted = df.melt(
    id_vars=['test preparation course'],
    value_vars=['math score', 'reading score', 'writing score'],
    var_name='Subject',
    value_name='Score'
)

plt.figure(figsize=(12, 7))
sns.boxplot(
    x='Subject',
    y='Score',
    hue='test preparation course',
    data=score_melted,
    palette='Set2'
)
plt.title('Score Variance by Test Preparation Course Completion', fontsize=16)
plt.xlabel('Subject', fontsize=12)
plt.ylabel('Score Distribution', fontsize=12)
plt.legend(title='Test Preparation Course')
plt.tight_layout()

plt.show()

sns.set_theme(style="whitegrid")

score_melted = df.melt(
    id_vars=['test preparation course'],
    value_vars=['math score', 'reading score', 'writing score'],
    var_name='Subject',
    value_name='Score'
)

plt.figure(figsize=(12, 7))
sns.boxplot(
    x='Subject',
    y='Score',
    hue='test preparation course',
    data=score_melted,
    palette='Set2'
)
plt.title('Score Variance by Test Preparation Course Completion', fontsize=16)
plt.xlabel('Subject', fontsize=12)
plt.ylabel('Score Distribution', fontsize=12)
plt.legend(title='Test Preparation Course')
plt.tight_layout()

plt.show()

sns.set_theme(style="ticks")
pp = sns.pairplot(df[score_columns + ['test preparation course']], hue='test preparation course', palette='Set1', diag_kind='kde')
pp.fig.suptitle('Pairwise Scatter Plots of Test Scores', y=1.02, fontsize=16)
plt.show()