# -*- coding: utf-8 -*-
"""shopify.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EOzTWyWwITXBMp2_F3xXkP-kj0VCPClo
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv("shopify_stock.csv")

df.head()

df.info()

df['date'] = pd.to_datetime(df['date'])

df.isnull().sum()

df.dropna()

plt.plot(df['date'],df['close'])
plt.title("Shopify's Close price over time")
plt.xlabel("Close Price")
plt.ylabel("Time")
plt.show()

df['daily_delta']=df['close'] - df['open']

df['daily_return']=(df['close']-df['open'])/df['open']

df.head()

df.tail()

plt.hist(df['daily_return'])
plt.title("Shopify's Daily Return Histogram")
plt.xlabel("Daily Return")
plt.ylabel("Frequency")
plt.show()

import seaborn as sns

sns.histplot(df['daily_return'],kde=True)
plt.title("Shopify's Daily Return Histogram")
plt.xlabel("Daily Return")
plt.ylabel("Frequency")
plt.show()