# -*- coding: utf-8 -*-
"""StudentPerformance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12b5kFte77u3EP5WOq4lWIyI6LVhDVDwt
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("StudentsPerformance.csv")

df.head()

df.tail()

df.info()

df.describe()

df.isnull().sum()

df.columns

df.shape

score_columns=['math score','reading score','writing score']

score_columns

df[score_columns].describe()

df[score_columns].mean()

df[score_columns].median()

df[score_columns].mode()

df[score_columns].std()

df[score_columns].quantile(0.25)

df[score_columns].quantile(0.50)

df[score_columns].quantile(0.75)

df['Total Score']=df['math score']+df['reading score']+df['writing score']

df['Total Score']

df['Percentage'] = (df['Total Score']/300)*100

df[['Total Score','Percentage']].head()

outlier_results = {}

for col in score_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

outliers = df[
    (df[col] < lower_limit) |
    (df[col] > upper_limit)
]
outlier_results[col] = outliers
print("Subject:", col)
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)
print("Number of Outliers:", len(outliers))

for subject, outliers in outlier_results.items():

    print("\nOutliers in", subject)

    if len(outliers) > 0:
        print(
            outliers[
                [
                    "gender",
                    "race/ethnicity",
                    "math score",
                    "reading score",
                    "writing score",
                    "Total Score",
                    "Percentage"
                ]
            ]
        )
    else:
        print("No outliers detected.")