# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZ3JvU_9jpJA5A5FxSXLms9bLkkCS_n4
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("healthcare_dataset (1).csv")

df["Medical_Code_Category"] = df["Medical_Code"].str.replace("ICD-10-", "")

df.head()

df.info()

df.describe()

df.isnull().sum()

df.columns

df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Year_Month'] = df['Date of Admission'].dt.to_period('M')

monthly_admissions = df.groupby('Year_Month').size()

monthly_admissions.head()

peak_month = monthly_admissions.idxmax()
peak_admissions = monthly_admissions.max()

print("Peak Admission Month:", peak_month)
print("Number of Admissions:", peak_admissions)

billing_data = df.groupby(
    ['Medical Condition', 'Insurance Provider']
)['Billing Amount'].sum().unstack(fill_value=0)

billing_data.plot(
    kind='bar',
    stacked=True,
    figsize=(12, 6)
)

plt.title('Billing Amount by Medical Condition and Insurance Provider')
plt.xlabel('Medical Condition')
plt.ylabel('Total Billing Amount')
plt.xticks(rotation=45)
plt.legend(title='Insurance Provider')
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))
sns.violinplot(
    data=df,
    x='Medical Condition',
    y='Billing Amount'
)

plt.title('Billing Amount Distribution by Medical Condition')
plt.xlabel('Medical Condition')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))

sns.violinplot(
    data=df,
    x='Insurance Provider',
    y='Billing Amount'
)

plt.title('Billing Amount Distribution by Insurance Provider')
plt.xlabel('Insurance Provider')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

print("Average Billing Amount by Medical Condition:")
print(df.groupby('Medical Condition')['Billing Amount'].mean())

print("\nAverage Billing Amount by Insurance Provider:")
print(df.groupby('Insurance Provider')['Billing Amount'].mean())

df ['Admission Month']=df['Date of Admission'].dt.month
df['Admission Month']

monthly_admissions = df.groupby('Admission Month').size()
monthly_admissions

plt.figure(figsize=(12, 6))
monthly_admissions.plot(kind="line",marker="o")
plt.title('Monthly Admissions')
plt.xlabel('Month')
plt.ylabel('Number of Admissions')
plt.xticks(rotation=45)
plt.grid()
plt.show()

df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])
df['Stay Duration'] = (df['Discharge Date'] - df['Date of Admission']).dt.days
correlation_matrix = df[["Age", "Stay Duration", "Billing Amount"]].corr()
correlation_matrix

sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()