# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Mp97youuSb9bq2qvLp6O2YgKAkg0xF3
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

data = pd.read_csv("AAPL.csv")

df = pd.DataFrame(data)

df.head()

df.tail()

df.info()

df.describe()

df.columns

df.isnull().sum()

df.dropna()

df.drop_duplicates()

average_open = df['Open'].mean()
print(average_open)

average_close = df['Close'].mean()
print(average_close)

maximum_high = df['High'].max()
print(maximum_high)

minimum_low = df['Low'].min()
print(minimum_low)

df['Daily_Delta'] = df['Close'] - df['Open']

df.head()

df['Daily_Delta'].sort_index()

df['Daily_Return'] = (df['Daily_Delta'] /df['Open']) * 100

df.head()

df['Daily_Return'].sort_index()

Average_volume = df['Volume'].mean()
Max_volume = df['Volume'].max()
Min_volume = df['Volume'].min()
print(Average_volume)
print(Max_volume)
print(Min_volume)

