# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZ3JvU_9jpJA5A5FxSXLms9bLkkCS_n4
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("healthcare_dataset.csv")

df["Medical_Code_Category"] = df["Medical_Code"].str.replace("ICD-10-", "")

df.head()

df.info()

df.describe()

df.isnull().sum()

df.dropna()

df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], format="%d-%m-%Y")
df["Discharge_Date"] = pd.to_datetime(df["Discharge_Date"], format="%d-%m-%Y")
df["hospital_stay_days"] = (df["Discharge_Date"] - df["Admission_Date"]).dt.days

df.head()

display(df[['Billing_Amount', 'hospital_stay_days']].describe())

